Repository ossf/security-baseline, pull requests merged in 2025-01, with the labels that each got.

#149 Adding Regulatory crosswalk mappings to VM category items
  baseline/OSPS-VM.yaml
Labels: enhancement, criteria

#141 Adding Regulatory crosswalk mappings to AC category items
  baseline/OSPS-AC.yaml
Labels: enhancement, criteria

#142 Adding Regulatory crosswalk mappings to BR category items
  baseline/OSPS-BR.yaml
Labels: enhancement, criteria

#143 Adding Regulatory crosswalk mappings to DO category items
  baseline/OSPS-DO.yaml
Labels: enhancement, criteria

#144 Adding Regulatory crosswalk mappings to GV category items
  baseline/OSPS-GV.yaml
Labels: enhancement, criteria

#145 Adding Regulatory crosswalk mappings to LE category items
  baseline/OSPS-LE.yaml
Labels: enhancement, criteria

#146 Adding Regulatory crosswalk mappings to QA category items
  baseline/OSPS-QA.yaml
Labels: enhancement, criteria

#140 Clarify OSPS-BR-01
  baseline/OSPS-BR.yaml
Labels: documentation, enhancement, criteria

#148 Adding Regulatory crosswalk mappings to SA category items
  baseline/OSPS-SA.yaml
Labels: enhancement, criteria

#158 Added lexicon entry for CRA
  baseline/lexicon.yaml
Labels: documentation

#160 Update missing rationale & implementation details for Governance criteria
  baseline/OSPS-GV.yaml
Labels: criteria

#161 Adjust documentation level requirements
  baseline/OSPS-DO.yaml
  baseline/OSPS-SA.yaml
Labels: criteria

#162 Increase maturity level for BR-10
  baseline/OSPS-BR.yaml
Labels: criteria

#154 Clarify that input and output interfaces means APIs.
  baseline/OSPS-SA.yaml
Labels: criteria

#166 Enhancement of SA rationales and implementation details
  baseline/OSPS-SA.yaml
  baseline/lexicon.yaml
Labels: criteria
