Repository ossf/security-baseline, pull requests merged in 2025-02, with the labels that each got.

#116 Add a maintenance process
  .github/workflows/test-build.yml
  .github/workflows/web-publish.yml
  .gitignore
  docs/index.md
  docs/maintenance.md
Labels: documentation, enhancement, help wanted

#186 Updated and extended dependency + SBOM criteria
  baseline/OSPS-QA.yaml
  baseline/lexicon.yaml
Labels: criteria

#159 Updates to Documentation criteria missing rationale and implementation details
  baseline/OSPS-DO.yaml
  baseline/lexicon.yaml
  docs/versions/devel.md
Labels: criteria

#193 Added revised controls.yaml
  CONTRIBUTING.md
  README.md
  baseline/OSPS-AC.yaml
  baseline/OSPS-BR.yaml
  baseline/OSPS-DO.yaml
  baseline/OSPS-GV.yaml
  baseline/OSPS-LE.yaml
  baseline/OSPS-QA.yaml
  baseline/OSPS-SA.yaml
  baseline/OSPS-VM.yaml
  baseline/frameworks.yaml
  baseline/lexicon.yaml
  cmd/internal/cmd/compile.go
  cmd/pkg/baseline/generator.go
  cmd/pkg/baseline/loader.go
  cmd/pkg/baseline/template-functions.go
  cmd/pkg/baseline/validator.go
  cmd/pkg/types/types.go
  cmd/template.md
  docs/maintenance.md
  governance/GOVERNANCE.md
Labels: criteria

#195 Add the FAQ
  docs/faq.md
  docs/index.md
Labels: documentation, enhancement

#227 Update lexicon.yaml with Scorecard entry
  baseline/lexicon.yaml
Labels: documentation, criteria

#232 Update OSPS-LE.yaml with mappings!
  baseline/OSPS-LE.yaml
Labels: criteria

#230 Update OSPS-DO.yaml minr mapping & maturity adjustments
  baseline/OSPS-DO.yaml
Labels: criteria

#234 Update OSPS-QA.yaml with mappings
  baseline/OSPS-QA.yaml
Labels: criteria

#235 Update OSPS-VM.yaml with amazing mappings!
  baseline/OSPS-VM.yaml
Labels: criteria

#229 Update OSPS-BR.yaml with control mappings & maturity for one item
  baseline/OSPS-BR.yaml
Labels: criteria
